# Generated by Django 3.2.2 on 2021-05-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagtype', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=120)),
            ],
        ),
    ]
