# Generated by Django 3.2.4 on 2021-08-07 08:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discovery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvitedUsers',
            new_name='InvitedUser',
        ),
    ]
