# Generated by Django 3.2.2 on 2021-05-06 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0002_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20)),
                ('author_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author', to='discovery.profile')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='discovery.tag')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target', to='discovery.profile')),
            ],
        ),
    ]
