# Generated by Django 3.2.4 on 2021-08-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0002_rename_invitedusers_inviteduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
