# Generated by Django 3.2.2 on 2021-05-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0003_usertag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='usertag',
            name='author_user',
        ),
        migrations.RemoveField(
            model_name='usertag',
            name='target_user',
        ),
        migrations.AddField(
            model_name='profile',
            name='given_tags',
            field=models.ManyToManyField(to='discovery.UserTag'),
        ),
        migrations.AddField(
            model_name='profile',
            name='received_tags',
            field=models.ManyToManyField(related_name='given_tags', to='discovery.UserTag'),
        ),
    ]
