# Generated by Django 3.2.4 on 2021-08-10 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0005_rename_value_tag__type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='InvitedUser',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
