# Generated by Django 3.2.2 on 2021-05-07 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0007_auto_20210507_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tagtype',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='given_tags',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='received_tags',
        ),
        migrations.DeleteModel(
            name='UserTag',
        ),
        migrations.AddField(
            model_name='tagassignment',
            name='giver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reciever', to='discovery.profile'),
        ),
        migrations.AddField(
            model_name='tagassignment',
            name='reciever',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='discovery.profile'),
        ),
        migrations.AddField(
            model_name='tagassignment',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='discovery.tag'),
        ),
    ]
