# Generated by Django 3.2.2 on 2021-05-07 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0008_auto_20210507_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagassignment',
            name='giver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reciever', to='discovery.profile'),
        ),
        migrations.AlterField(
            model_name='tagassignment',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='discovery.profile'),
        ),
    ]
