# Generated by Django 3.2.6 on 2021-08-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0010_auto_20210806_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='discovery.Tag', verbose_name='Tags'),
        ),
    ]
