# Generated by Django 3.2.6 on 2021-08-06 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0014_auto_20210806_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='invitation_code',
        ),
    ]
