# Generated by Django 3.2.4 on 2021-09-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
