# Generated by Django 3.2.4 on 2021-09-23 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_is_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_webpush',
        ),
    ]
