# Generated by Django 3.2.4 on 2021-11-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_notification_is_webpush'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_webpush',
            field=models.BooleanField(default=False),
        ),
    ]
