# Generated by Django 3.2.4 on 2021-08-27 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210827_0616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagemodel',
            options={},
        ),
        migrations.RenameField(
            model_name='messagemodel',
            old_name='user',
            new_name='sender',
        ),
        migrations.RemoveField(
            model_name='messagemodel',
            name='body',
        ),
        migrations.RemoveField(
            model_name='messagemodel',
            name='recipient',
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chats/'),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='to_session', to='chat.chatsession', verbose_name='session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='text',
            field=models.CharField(default='empty', max_length=512),
            preserve_default=False,
        ),
    ]
