# Generated by Django 3.2.4 on 2021-08-27 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210827_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession', verbose_name='session'),
        ),
    ]
