# Generated by Django 3.2.4 on 2021-08-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_rename_messagemodel_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsessionuser',
            options={'ordering': ('session__is_expired',)},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='chatsession',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='room_name',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
