# Generated by Django 3.2.4 on 2021-08-31 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20210830_0615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsessionuser',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='is_expired',
        ),
    ]
